name: Compile AdGuardHome LuCI App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Get-Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      date_version: ${{ steps.date_version.outputs.version }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Generate New Version with Date
        id: date_version
        run: |
          # Base version
          BASE_VERSION="1.8"
          # Get current date in YYYYMMDD format
          DATE_SUFFIX=$(date '+%Y%m%d')
          # Combine to form the version number
          NEW_VERSION="${BASE_VERSION}.${DATE_SUFFIX}"
          echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "New Version: ${NEW_VERSION}"

          # Update version in Makefile
          sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=${NEW_VERSION}/" ./Makefile

      - name: Current Version in Makefile
        id: version
        run: |
          echo "version=$(grep 'PKG_VERSION:=' ./Makefile |awk -F ':=' '{print $2}')" >> $GITHUB_OUTPUT
          echo "Current Makefile Version: $(grep 'PKG_VERSION:=' ./Makefile |awk -F ':=' '{print $2}')"

  Compile:
    runs-on: ubuntu-latest
    needs: Get-Version
    steps:
      - name: Clone AdGuardHome Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Update Makefile Version
        run: |
          sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=${{ needs.Get-Version.outputs.date_version }}/" ./Makefile
          cat ./Makefile

      - name: Apt Update
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install curl git tar zstd

      - name: Install OpenWrt SDK
        run: |
          curl -SLk --connect-timeout 30 --retry 2 "https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2" -o "/tmp/SDK.tar.bz2"
          cd /tmp
          tar xjf SDK.tar.bz2
          mv "OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64" "SDK"

      - name: Install OpenWrt SNAPSHOT SDK
        run: |
          curl -SLk --connect-timeout 30 --retry 2 "https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst" -o "/tmp/SNAPSDK.tar.zst"
          cd /tmp
          zstd -d SNAPSDK.tar.zst
          tar xf SNAPSDK.tar
          mv "openwrt-sdk-x86-64_gcc-13.3.0_musl.Linux-x86_64" "SNAPSDK"

      - name: Copy AdGuardHome Source Codes
        run: |
          mkdir -p /tmp/SDK/package/luci-app-adguardhome
          mkdir -p /tmp/SNAPSDK/package/luci-app-adguardhome
          rsync -avh "." "/tmp/SDK/package/luci-app-adguardhome"
          rsync -avh "." "/tmp/SNAPSDK/package/luci-app-adguardhome"

      - name: Compile po2lmo
        run: |
          cd /tmp/SDK/package/
          if [ -d "luci-app-adguardhome/tools/po2lmo" ]; then
            pushd luci-app-adguardhome/tools/po2lmo
            make && sudo make install
            popd
          fi
          cd /tmp/SNAPSDK/package/
          if [ -d "luci-app-adguardhome/tools/po2lmo" ]; then
            pushd luci-app-adguardhome/tools/po2lmo
            make && sudo make install
            popd
          fi

      - name: Compile AdGuardHome IPK
        run: |
          cd /tmp/SDK
          ./scripts/feeds update -a
          ./scripts/feeds install luci-app-adguardhome
          echo 'CONFIG_PACKAGE_luci-app-adguardhome=y'>.config
          make defconfig
          make package/luci-app-adguardhome/compile V=99

      - name: Compile AdGuardHome APK
        run: |
          cd /tmp/SNAPSDK
          ./scripts/feeds update -a
          ./scripts/feeds install luci-app-adguardhome
          echo 'CONFIG_PACKAGE_luci-app-adguardhome=y'>.config
          make defconfig
          make package/luci-app-adguardhome/compile V=99

      - name: Create Version Info
        run: |
          mkdir -p ./artifacts
          echo "v${{ needs.Get-Version.outputs.date_version }}" > ./artifacts/version.txt

      - name: Move Packages to Upload Directory
        run: |
          # Copy IPK from legacy SDK
          cp /tmp/SDK/bin/ar71xx/packages/base/luci-app-adguardhome_*_all.ipk "./artifacts/"
          cp /tmp/SDK/bin/ar71xx/packages/base/luci-i18n-adguardhome-*_all.ipk "./artifacts/"

          # Copy APK from SNAPSHOT SDK
          cp /tmp/SNAPSDK/bin/packages/x86_64/base/luci-app-adguardhome-*.apk "./artifacts/"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AdGuardHome-Packages-v${{ needs.Get-Version.outputs.date_version }}
          path: |
            ./artifacts/*
          retention-days: 30
